# Generated by Django 2.2 on 2019-06-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_type', models.CharField(max_length=10)),
                ('os_name', models.CharField(max_length=25)),
                ('hostname', models.CharField(max_length=30)),
                ('ip_address', models.CharField(max_length=17)),
                ('mac_address', models.CharField(max_length=25)),
                ('network_address', models.CharField(max_length=25)),
                ('subnet_mask', models.CharField(max_length=17)),
                ('broadcast_address', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_time', models.DateTimeField(verbose_name='date of launch')),
            ],
        ),
    ]
