# Generated by Django 2.2 on 2019-06-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getmydata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homehost',
            name='scan_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='getmydata.Scan'),
            preserve_default=False,
        ),
    ]
