# Generated by Django 2.2 on 2019-06-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getmydata', '0002_homehost_scan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homehost',
            old_name='scan_id',
            new_name='scan',
        ),
    ]
