# Generated by Django 2.2 on 2019-06-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getmydata', '0003_auto_20190614_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homehost',
            name='scan',
        ),
    ]
