# Generated by Django 2.2 on 2019-06-14 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getmydata', '0004_remove_homehost_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='homehost',
            name='scan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='getmydata.Scan'),
        ),
    ]
