# Generated by Django 2.2 on 2019-06-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getmydata', '0005_homehost_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homehost',
            name='broadcast_address',
            field=models.CharField(default='127.0.0.255', max_length=17),
        ),
        migrations.AlterField(
            model_name='homehost',
            name='hostname',
            field=models.CharField(default='localhost', max_length=30),
        ),
        migrations.AlterField(
            model_name='homehost',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=17),
        ),
        migrations.AlterField(
            model_name='homehost',
            name='mac_address',
            field=models.CharField(default='MAC Address unknown', max_length=25),
        ),
        migrations.AlterField(
            model_name='homehost',
            name='network_address',
            field=models.CharField(default='127.0.0.0/0', max_length=25),
        ),
        migrations.AlterField(
            model_name='homehost',
            name='os_name',
            field=models.CharField(default='Unknown OS Name', max_length=25),
        ),
        migrations.AlterField(
            model_name='homehost',
            name='os_type',
            field=models.CharField(default='Unknown OS Type', max_length=10),
        ),
        migrations.AlterField(
            model_name='homehost',
            name='subnet_mask',
            field=models.CharField(default='0.0.0.0', max_length=17),
        ),
    ]
