# Generated by Django 2.2 on 2019-06-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getmydata', '0007_auto_20190617_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homehost',
            name='mac_address',
            field=models.CharField(default='Unknown MAC Address', max_length=25),
        ),
        migrations.AlterField(
            model_name='scan',
            name='launch_time',
            field=models.CharField(default='Time of scan is unknown', max_length=30),
        ),
    ]
