# Generated by Django 2.2 on 2019-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getmydata', '0010_scan_icmp_scan_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='tcp_scan_time',
            field=models.FloatField(default=0.0),
        ),
    ]
