# Generated by Django 2.2 on 2019-06-20 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('getmydata', '0011_scan_tcp_scan_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 9, 1, 18, 794734, tzinfo=utc)),
        ),
    ]
