# Generated by Django 2.2 on 2019-06-20 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getmydata', '0012_scan_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
