# Generated by Django 2.2 on 2019-06-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('getmydata', '0006_auto_20190614_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICMPScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=17)),
                ('scan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='getmydata.Scan')),
            ],
        ),
    ]
