# Generated by Django 2.2 on 2019-06-18 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getmydata', '0011_scan_tcp_scan_time'),
        ('icmpscan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCPScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=17)),
                ('scan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='getmydata.Scan')),
            ],
        ),
    ]
